FROM mysql:latest

ENV MYSQL_ALLOW_EMPTY_PASSWORD="yes"
ENV MYSQL_DATABASE="cqrs_read"

COPY ./mySqlSeed.sql/ /docker-entrypoint-initdb.d/

EXPOSE 3306

HEALTHCHECK --interval=10s --timeout=20s --start-period=5s --retries=10 \
  CMD mysqladmin ping -h localhost || exit 1
